palette = 'colors'

[palettes.colors]
background = '{{colors.background.default.hex}}'
primary = '{{colors.primary.default.hex}}'
color0 = '{{colors.source_color.default.hex}}'
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[username]
format = " [â•­â”€$user]($style)@"
show_always = true
style_root = "color0"
style_user = "color0"

# Second param
[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = false
style = "color0"
#trim_at = "-"

# Third param
[directory]
style = "primary"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "repo: "

# Fourth param
[sudo]
disabled = false

# Before all the version info (python, nodejs, php, etc.)
[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
deleted = "x"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
style = "white"

# Last param in the first line/row
[cmd_duration]
disabled = false
format = "took [$duration]($style)"
min_time = 1
style = "primary"

## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
charging_symbol = "ï–ƒ"
disabled = true
discharging_symbol = "ï–‚"
full_symbol = "ï•¸"

[[battery.display]] # "bold red" style when capacity is between 0% and 15%
disabled = true
style = "bold red"
threshold = 15

[[battery.display]] # "bold yellow" style when capacity is between 15% and 50%
disabled = true
style = "bold yellow"
threshold = 50

[[battery.display]] # "bold green" style when capacity is between 50% and 80%
disabled = true
style = "bold green"
threshold = 80

# Prompt: optional param 1
[time]
disabled = false
format = " ğŸ•™ $time($style)\n"
style = "bright-white"
time_format = "%T"

# Prompt: param 2
[character]
error_symbol = " [Ã—](color0)"
success_symbol = " [â•°â”€Î»](color0)"

# SYMBOLS
[status]
disabled = false
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
symbol = "ğŸ”´"
style = "color0"

[aws]
symbol = "îŒ½ "
style = "primary"

[conda]
symbol = "ï„Œ "
style = "primary"

[dart]
symbol = "î˜ "
style = "primary"

[docker_context]
symbol = "ïŒˆ "
style = "primary"

[elixir]
symbol = "î‰µ "
style = "primary"

[elm]
symbol = "î˜¬ "
style = "primary"

[git_branch]
symbol = "ï˜ "
style = "primary"

[golang]
symbol = "î˜§ "
style = "primary"

[hg_branch]
symbol = "ï˜ "
style = "primary"

[java]
symbol = "î‰– "
style = "primary"

[julia]
symbol = "î˜¤ "
style = "primary"

[nim]
symbol = "ïš¤ "
style = "primary"

[nix_shell]
symbol = "ï‹œ "
style = "primary"

[nodejs]
symbol = "î‰ "
style = "primary"

[package]
symbol = "ï£– "
style = "primary"

[perl]
symbol = "î© "
style = "primary"

[php]
symbol = "î˜ˆ "
style = "primary"

[python]
symbol = "î˜† "
style = "primary"

[ruby]
symbol = "îˆ¾ "
style = "primary"

[rust]
symbol = "î¨ "
style = "primary"

[swift]
symbol = "ï¯£ "
style = "primary"
